### ISSUE TITLE
BasicSpline is an undefined class. oSpine typo.

### ISSUE THREAD

**Issue by mosri** [leap71/LEAP71_ShapeKernel#10]
BasicSpline() is not defined anywhere. What should it be?

Minor typos should be fixed, oSpine is written instead of oSpline.

<img width="834" alt="Screenshot 2024-03-25 at 9 05 02 PM" src="https://github.com/leap71/LEAP71_ShapeKernel/assets/8907920/55d67f19-8b77-4a04-ac58-2e79f64e25c7">

**Comment by josefinelissner** [comment]
Hi, @mosri !
Thanks for reading so carefully. I fixed the typos and added a sentence about the BaseSpline class, that returns a preset spline object.
