### ISSUE TITLE
Log error when attempting to run ShapeKernel the first time

### ISSUE THREAD

**Issue by 5RIndustries** [leap71/LEAP71_ShapeKernel#3]
I got an error stating I had no log file created before trying to execute the command Go(), or something to that effect, the first time I tried to run one of the examples.  I took the log entry command out of catch and ran it again and it worked.  Tried running it a second time with the log command added back to the catch and it worked.  For newbies like me, probably want to have them run the module first before creating the log (or maybe that's just a newb error?).

**Comment by josefinelissner** [comment]
Hi, @outlaw4shrt !

I think the issue you are describing was the following: If you are starting the program, you go into this try-bracket and it tries to initialize the PicoGK library and run the task. If something goes wrong in there and an exception is thrown, the program jumps to the catch-bracket which prints out the error message. In earlier versions we used the PicoGK log command to print out an error if the PicoGK library was not initialized correctly. Now if the library was not initialized correctly, there is no log command available. I updated it in all out published examples to the Console.WriteLine() function which is always available independent of PicoGK's state.


Before:
```
try
{
    PicoGK.Library.Go(
        0.1f,
        MyTasks.Task
        );
    Library.Log("Finished Task successfully.");
}
catch (Exception e)
{
    Library.Log("Failed to run Task.");
    Library.Log(e.ToString());
}
```

After:
```
try
{
    PicoGK.Library.Go(
        0.1f,
        MyTasks.Task
        );
    Library.Log("Finished Task successfully.");
}
catch (Exception e)
{
    Console.WriteLine("Failed to run Task.");
    Console.WriteLine(e.ToString());
}
```
