### ISSUE TITLE
ExampleSpline and workflows based on imported STLs

### ISSUE THREAD

**Issue by JimJoseStudent** [leap71/LEAP71_ShapeKernel#4]
First of all, thank you so much for your outstanding work on developing this tool. It is quiet a powerful tool once its established I feel. I am a new research student in the field of modelling optimised cooling channels to be purpose designed for AM. I have started working on PicoGK a few weeks back and have been spending a couple hours on this every week to explore its opportunities to see if it is applicable for my work. But I have had some real struggle getting into developing my own models mainly due to not being a native programmer and also due to the lack of comments in some of the examples. So, I'm hoping that someone can shed some light into these areas of the shapeKernal so I can have a better understanding of how to work with PicoGK. 

 As for the list of things I'm looking at is.

1) How can we generate pipe at a certain distance from a surface? (point of focus being how can we make designs by understanding the models already loaded in voxels)
For example, say there is an imported STL model that has been converted into voxels. But then how can you do operations or designs on these voxels generated such as adding a fillet or a pipe within it at a certain distance. I find it to be an essential tool for any modelling tool where you can add stuff to a model that is loaded or make additions based on it. 

2) I have been playing around with pipe modulations and splines where I can make the pipe longer or bend in certain directions. But if i want it to be condition based, i.e. make pipes that merge or stay at a distance from surface how can i implement that? 
The example codes of shape Kernal with some form of condition-based addition of voxels would be nice. let's say if i want to create a pipe or screw hole based on a variables value set to 2/3/4 then the number of pipes or screws generated would be based on that would be really helpful. I feel it's something similar to the HelixHX model but not filling a space but generate based on a condition. 

3) some comments on examples of PicoGK shapeKernals would be nice. The spline code used in the example Spline doesn't have any comments on what the parameters are assigned to new vector 3 are and I couldn't figure out what each of these variables are and what are the parameters used in it. So, in this case why are the values assigned to new Vector 3 (0,40,0) my understanding is that it's a coordinate but is there any specific format to selecting these coordinates? or can I choose any coordinates?

public class ExampleSpline : ISpline
{
    protected ControlPointSpline m_oBSpline;
    public ExampleSpline()
    {
        List<Vector3> aControlPoints = new List<Vector3>() {
            new Vector3(0, 0, 0),
            new Vector3(0, 40, 0),
            new Vector3(0, 50, 20),
            new Vector3(0, 60, 60),
        };
        m_oBSpline = new ControlPointSpline(aControlPoints);
   }
    
Any help on this is much appreciated. 

Kind regards, 
Jim

**Comment by josefinelissner** [comment]
@JimJoseStudent Regarding your third point: I just added some comments to the code. The snippet that you asked about is using a B-Spline (in the ShapeKernel library it is a ControlPointSpline object) that is defined via a few control points.
Take a look at this: https://en.wikipedia.org/wiki/B-spline

![B-spline_curve](https://github.com/leap71/LEAP71_ShapeKernel/assets/44703282/2387d264-71ee-4e2d-a116-eedb4d596471)

aControlPoints is a list that essential holds the little black dots from the picture. The control points are defined via their x-y-z coordinates in space. Since B-Splines are continuous, the information about the smooth curve is calculated and stored inside the m_oBSpline object. If you call m_oBSpline.aGetPoints(nSamples = 500) you will get a list of 500 points that lie on this smooth curve. If you change nSamples you can sample more or less positions along the spline. 

The x-y-z coordinates (e.g Vector3(0, 40, 0)) are just hard-coded in this example to make up a somewhat meaningful spline.

**Comment by josefinelissner** [comment]
@JimJoseStudent 

To give an example in response to your first questions, I am sharing here an example of a (very) simple mould, where a "walk-on-surface" is performed by a turtle object (inspired by turtle graphics). The progress of the walk is color-coded and looks like this:

<img width="1006" alt="Screenshot 2024-03-07 at 8 42 54 PM" 
src="https://github.com/leap71/LEAP71_ShapeKernel/assets/44703282/1c5f5681-2ba8-4ebb-a0b3-10a49bdb4623">

Feel free to check out the attached code example. The general workflow would be:
1) Import and voxelize STL mesh or (like in this case) generate preset mould object
2) Offset and smoothen the object slightly. You would not design a channel in a constant distance to an object's surface, but offset the object first and then design a channel right on that surface.
3) Query bounding box and use raycasting to get a first point on the surface.
4) Use a sequence of moves and bGetClosestPointOnSurface()-function to walk across the surface.
5) Record the trace points of the walk and post-process them if necessary (e.g. smoothing)


[Ex_SurfaceTurtleWalkShowCase.txt](https://github.com/leap71/LEAP71_ShapeKernel/files/14527350/Ex_SurfaceTurtleWalkShowCase.txt)


You can run this example by copying the attached code to you VS project. Call `SurfaceWalkShowCase.Task` from your Program.cs and set voxelsize = 0.3mm
Please update to the latest ShapeKernel version (no earlier than 2024-03-07)

**Comment by JimJoseStudent** [comment]
Hey Josefine, Sorry for the delay in response, I had a few exams I was preoccupied with. 
I just tried to access the code but it is not working. 

![image](https://github.com/leap71/LEAP71_ShapeKernel/assets/151611137/c6cfa075-d5ac-4acc-b928-7dcaa3d97605)

**Comment by josefinelissner** [comment]
You only need to click on this hyperlink in my previous post and it should download the file: 
<img width="261" alt="image" src="https://github.com/leap71/LEAP71_ShapeKernel/assets/44703282/4eefda50-e2d1-4508-99d0-b85fb6e3c951">

Once downloaded, rename from .txt to .cs (this forum here let's me only share txt-files) and copy it into your VS Project.
Make sure PicoGK and ShapeKernel are up to date.

**Comment by JimJoseStudent** [comment]
HI based on your example i have been able to create a few different implementations of this for spiral and zigzag patterns. But im still struggling to my own fault for what im targetting. 

Mean while i have a new question. If i wanted to use SDF instead of raycasting does PicoGK have a way to access SDF? As i understand the application of logo or text on a surface was implemented using this method?
